### ISSUE TITLE
Question:  how to use the sliders for the weighting of the metrics?

### ISSUE THREAD

**Issue by VictorvandenHoven** [CDrummond/lms-blissmixer#6]
Hi,

Trying out your lsm-blissmixer software.
Thank you for al your work.

I would like to try out some changes in the weighing of the metrics.
If I increase for instance the chroma metric type from 50 to 60, the total of all the weighing values becomes 110.
Will the percentual weighing value of all  metric types then be adapted  with factor  (100/110)  or not?
What exactly is the formula you use?

Kind regards,

Victor

**Comment by CDrummond** [comment]
The weighting is normalised. So, each is taken as a percentage of the total. The code for this is:

```perl
sub _weightParam {
    my @weights = ();
    my $tempo = int($prefs->get('weight_tempo') || 5);
    my $timbre = int($prefs->get('weight_timbre') || 35);
    my $loudness = int($prefs->get('weight_loudness') || 10);
    my $chroma = int($prefs->get('weight_chroma') || 50);
    
    my $total = $tempo + $timbre + $loudness + $chroma;
    $tempo = (($tempo / $total) * 100.0) / 5.0;
    $timbre = (($timbre / $total) * 100.0) / 35.0;
    $loudness = (($loudness / $total) * 100.0) / 10.0;
    $chroma = (($chroma / $total) * 100.0) / 50.0;

    push @weights, $tempo;
    for (my $i = 0; $i < 7; $i++) {
        push @weights, $timbre;
    }
    for (my $i = 0; $i < 2; $i++) {
        push @weights, $loudness;
    }
    for (my $i = 0; $i < 10; $i++) {
        push @weights, $chroma;
    }

    my $str = join(",", @weights);
    return $str;
}
```

...therefore if default values are used, each individual bliss metric is given a weighting of 1 (which is its default).
